# Generated by Django 4.0.6 on 2022-07-30 17:09

import areas.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('types_of_identity_documents', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParties',
            fields=[
                ('id', areas.models.UnsignedAutoField(primary_key=True, serialize=False, unique=True)),
                ('identity_document', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('second_surname', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_names', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
                ('types_of_identity_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_of_identity_documents_third_parties', to='types_of_identity_documents.typesofidentitydocuments')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', areas.models.UnsignedAutoField(primary_key=True, serialize=False, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_of_entry', models.DateTimeField()),
                ('status', models.CharField(choices=[('0', 'Active'), ('1', 'Inactive')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_employees', to='areas.areas')),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_parties_employees', to='employees.thirdparties')),
            ],
        ),
    ]
