# Generated by Django 4.0.6 on 2022-08-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='third_party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='third_parties_employees', to='employees.thirdparties'),
        ),
    ]
