/**
 * Declare action types for reducers
 */
export const EMPLOYEES_LOADING = 'EMPLOYEES_LOADING';
export const EMPLOYEES_FAILED = 'EMPLOYEES_FAILED';
export const ADD_EMPLOYEES = 'ADD_EMPLOYEES';

export const COUNTRIES_LOADING = 'COUNTRIES_LOADING';
export const COUNTRIES_FAILED = 'COUNTRIES_FAILED';
export const ADD_COUNTRIES = 'ADD_COUNTRIES';

export const AREAS_LOADING = 'AREAS_LOADING';
export const AREAS_FAILED = 'AREAS_FAILED';
export const ADD_AREAS = 'ADD_AREAS';

export const TYPES_OF_IDENTITY_DOCUMENTS_LOADING = 'TYPES_OF_IDENTITY_DOCUMENTS_LOADING';
export const TYPES_OF_IDENTITY_DOCUMENTS_FAILED = 'TYPES_OF_IDENTITY_DOCUMENTS_FAILED';
export const ADD_TYPES_OF_IDENTITY_DOCUMENTS = 'ADD_TYPES_OF_IDENTITY_DOCUMENTS';
