# Generated by Django 4.0.6 on 2022-07-29 21:55

import areas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfIdentityDocuments',
            fields=[
                ('id', areas.models.UnsignedAutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
            ],
        ),
    ]
